#!/usr/bin/env python

#Author: Sierra Williams
#Date Created: 07/12/16
#Date Modeified: 07/12/16

### What script does ###
# Send Goal poses to Hero and Intruder #
# listen to intruder sensor topic #
# get coordinated of node from json script #
# Publish goal poses #
